### ISSUE TITLE
[Improvement] Overlay Behaviour 

### ISSUE THREAD

**Issue by LuanTeles** [jordywastaken/ip_text#2]
I don't know if it's possible, but could the overlays auto-hide while in the music/video/photo viewer and when the web browser is open, just like the official xmb_plugin.sprx behaviour ?

**Comment by jordywastaken** [comment]
I'm on it captain

**Comment by jordywastaken** [comment]
Aye aye captain, it is done, will update the repo and push a new release in a few minutes.
So, in order to recreate the official xmb_plugin behaviour i added a check to verify if the current xmb_plugin.sprx is the cex one or a debug one, if it is a debug one i just replace the text, the behaviour should be the same. If it is the regular one i append the ip_text widget here:
![hon hon hon](https://user-images.githubusercontent.com/113445560/200563893-19c1586d-9de8-46e9-ae8b-b433760044ff.PNG)
From my test i believe it behave the same as the official one

**Comment by LuanTeles** [comment]
That's strage yesterday when i opened this issue it was showing in those conditions, today without updating the sprx, the behaviour is right lol.

Thank you so much for the new version :) and the plugin.
